spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ipdb
  h2:
    console:
      enabled: true
  config:
    import: optional:file:.env[.properties]

ip-stack:
  api-url: http://api.ipstack.com/
  api-key: ${API_KEY:default}